<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Section 12 Relationships in data | MPS223 - Mathematics and Statistics in Action</title>
  <meta name="description" content="MPS223" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Section 12 Relationships in data | MPS223 - Mathematics and Statistics in Action" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="MPS223" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Section 12 Relationships in data | MPS223 - Mathematics and Statistics in Action" />
  
  <meta name="twitter:description" content="MPS223" />
  

<meta name="author" content="" />


<meta name="date" content="2026-02-03" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="computing-using-loops.html"/>
<link rel="next" href="imputing-missing-data.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.2/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.2/leaflet-providers-plugin.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MPS223</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About these notes</a></li>
<li class="chapter" data-level="1" data-path="set-up-your-r-environment.html"><a href="set-up-your-r-environment.html"><i class="fa fa-check"></i><b>1</b> Set up your R environment</a></li>
<li class="chapter" data-level="2" data-path="project-overview.html"><a href="project-overview.html"><i class="fa fa-check"></i><b>2</b> Project overview</a></li>
<li class="part"><span><b>I Data processing</b></span></li>
<li class="chapter" data-level="3" data-path="importing-data.html"><a href="importing-data.html"><i class="fa fa-check"></i><b>3</b> Importing data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="importing-data.html"><a href="importing-data.html#importing-a-.csv-file"><i class="fa fa-check"></i><b>3.1</b> Importing a .csv file</a></li>
<li class="chapter" data-level="3.2" data-path="importing-data.html"><a href="importing-data.html#importing-excel-.xlsx-files"><i class="fa fa-check"></i><b>3.2</b> Importing Excel .xlsx files</a></li>
<li class="chapter" data-level="3.3" data-path="importing-data.html"><a href="importing-data.html#importing-a-plain-text-file"><i class="fa fa-check"></i><b>3.3</b> Importing a plain text file</a></li>
<li class="chapter" data-level="3.4" data-path="importing-data.html"><a href="importing-data.html#importing-online-data"><i class="fa fa-check"></i><b>3.4</b> Importing online data</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="strings.html"><a href="strings.html"><i class="fa fa-check"></i><b>4</b> Strings</a>
<ul>
<li class="chapter" data-level="4.1" data-path="strings.html"><a href="strings.html#example-fictitous-exam-mark-data"><i class="fa fa-check"></i><b>4.1</b> Example: (fictitous) exam mark data</a></li>
<li class="chapter" data-level="4.2" data-path="strings.html"><a href="strings.html#importing-text-data-with-read_lines"><i class="fa fa-check"></i><b>4.2</b> Importing text data with <code>read_lines()</code></a></li>
<li class="chapter" data-level="4.3" data-path="strings.html"><a href="strings.html#finding-and-replacing-characters-in-strings"><i class="fa fa-check"></i><b>4.3</b> Finding (and replacing) characters in strings</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="strings.html"><a href="strings.html#finding-text-with-str_which"><i class="fa fa-check"></i><b>4.3.1</b> Finding text with <code>str_which()</code></a></li>
<li class="chapter" data-level="4.3.2" data-path="strings.html"><a href="strings.html#escape-characters-and-regular-expressions"><i class="fa fa-check"></i><b>4.3.2</b> Escape characters and regular expressions</a></li>
<li class="chapter" data-level="4.3.3" data-path="strings.html"><a href="strings.html#replacing-or-removing-text"><i class="fa fa-check"></i><b>4.3.3</b> Replacing or removing text</a></li>
<li class="chapter" data-level="4.3.4" data-path="strings.html"><a href="strings.html#removing-white-space-at-startend-of-strings"><i class="fa fa-check"></i><b>4.3.4</b> Removing white space at start/end of strings</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="strings.html"><a href="strings.html#subsetting-strings"><i class="fa fa-check"></i><b>4.4</b> Subsetting strings</a></li>
<li class="chapter" data-level="4.5" data-path="strings.html"><a href="strings.html#making-a-data-frame"><i class="fa fa-check"></i><b>4.5</b> Making a data frame</a></li>
<li class="chapter" data-level="4.6" data-path="strings.html"><a href="strings.html#exercise"><i class="fa fa-check"></i><b>4.6</b> Exercise</a></li>
<li class="chapter" data-level="4.7" data-path="strings.html"><a href="strings.html#further-reading"><i class="fa fa-check"></i><b>4.7</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="manipulating-data-frames---recap.html"><a href="manipulating-data-frames---recap.html"><i class="fa fa-check"></i><b>5</b> Manipulating data frames - recap</a>
<ul>
<li class="chapter" data-level="5.1" data-path="manipulating-data-frames---recap.html"><a href="manipulating-data-frames---recap.html#chaining-commands-together-with-the-pipe-operator"><i class="fa fa-check"></i><b>5.1</b> Chaining commands together with the pipe operator <code>%&gt;%</code></a></li>
<li class="chapter" data-level="5.2" data-path="manipulating-data-frames---recap.html"><a href="manipulating-data-frames---recap.html#ordering-the-rows-by-a-variable-with-the-arrange-command"><i class="fa fa-check"></i><b>5.2</b> Ordering the rows by a variable with the <code>arrange()</code> command</a></li>
<li class="chapter" data-level="5.3" data-path="manipulating-data-frames---recap.html"><a href="manipulating-data-frames---recap.html#selecting-rows-with-the-filter-command"><i class="fa fa-check"></i><b>5.3</b> Selecting rows with the <code>filter()</code> command</a></li>
<li class="chapter" data-level="5.4" data-path="manipulating-data-frames---recap.html"><a href="manipulating-data-frames---recap.html#viewing-and-extracting-data-from-a-column"><i class="fa fa-check"></i><b>5.4</b> Viewing and extracting data from a column</a></li>
<li class="chapter" data-level="5.5" data-path="manipulating-data-frames---recap.html"><a href="manipulating-data-frames---recap.html#creating-new-columns-in-a-data-frame-with-the-mutate-command"><i class="fa fa-check"></i><b>5.5</b> Creating new columns in a data frame with the <code>mutate()</code> command</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="summary-statistics---recap.html"><a href="summary-statistics---recap.html"><i class="fa fa-check"></i><b>6</b> Summary statistics - recap</a>
<ul>
<li class="chapter" data-level="6.1" data-path="summary-statistics---recap.html"><a href="summary-statistics---recap.html#calculating-summary-statistics-with-the-summary-command"><i class="fa fa-check"></i><b>6.1</b> Calculating summary statistics with the <code>summary()</code> command</a></li>
<li class="chapter" data-level="6.2" data-path="summary-statistics---recap.html"><a href="summary-statistics---recap.html#calculating-individual-summary-statistics"><i class="fa fa-check"></i><b>6.2</b> Calculating individual summary statistics</a></li>
<li class="chapter" data-level="6.3" data-path="summary-statistics---recap.html"><a href="summary-statistics---recap.html#computing-summaries-per-group"><i class="fa fa-check"></i><b>6.3</b> Computing summaries per group</a></li>
<li class="chapter" data-level="6.4" data-path="summary-statistics---recap.html"><a href="summary-statistics---recap.html#exercise-1"><i class="fa fa-check"></i><b>6.4</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="missing-data.html"><a href="missing-data.html"><i class="fa fa-check"></i><b>7</b> Missing data</a>
<ul>
<li class="chapter" data-level="7.1" data-path="missing-data.html"><a href="missing-data.html#na"><i class="fa fa-check"></i><b>7.1</b> <code>NA</code></a></li>
<li class="chapter" data-level="7.2" data-path="missing-data.html"><a href="missing-data.html#functions-and-na"><i class="fa fa-check"></i><b>7.2</b> Functions and <code>NA</code></a></li>
</ul></li>
<li class="part"><span><b>II Plotting data</b></span></li>
<li class="chapter" data-level="8" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html"><i class="fa fa-check"></i><b>8</b> Making plots with <code>ggplot2</code> - recap</a>
<ul>
<li class="chapter" data-level="8.1" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#the-general-syntax"><i class="fa fa-check"></i><b>8.1</b> The general syntax</a></li>
<li class="chapter" data-level="8.2" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#scatter-plots"><i class="fa fa-check"></i><b>8.2</b> Scatter plots</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#annotating-a-scatter-plot"><i class="fa fa-check"></i><b>8.2.1</b> Annotating a scatter plot</a></li>
<li class="chapter" data-level="8.2.2" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#adding-a-trend"><i class="fa fa-check"></i><b>8.2.2</b> Adding a trend</a></li>
<li class="chapter" data-level="8.2.3" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#representing-more-than-two-variables-on-a-scatter-plot"><i class="fa fa-check"></i><b>8.2.3</b> Representing more than two variables on a scatter plot</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#histograms"><i class="fa fa-check"></i><b>8.3</b> Histograms</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#customising-a-histogram-plot-in-r"><i class="fa fa-check"></i><b>8.3.1</b> Customising a histogram plot in R</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#box-plots"><i class="fa fa-check"></i><b>8.4</b> Box plots</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#adding-the-observations-to-a-box-plot"><i class="fa fa-check"></i><b>8.4.1</b> Adding the observations to a box plot</a></li>
<li class="chapter" data-level="8.4.2" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#violin-plots"><i class="fa fa-check"></i><b>8.4.2</b> Violin plots</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#global-aesthetics"><i class="fa fa-check"></i><b>8.5</b> ‘Global’ aesthetics</a></li>
<li class="chapter" data-level="8.6" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#facets"><i class="fa fa-check"></i><b>8.6</b> Facets</a></li>
<li class="chapter" data-level="8.7" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#exBrexitPlots"><i class="fa fa-check"></i><b>8.7</b> Exercises</a></li>
<li class="chapter" data-level="8.8" data-path="making-plots-with-ggplot2---recap.html"><a href="making-plots-with-ggplot2---recap.html#further-reading-1"><i class="fa fa-check"></i><b>8.8</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html"><i class="fa fa-check"></i><b>9</b> Presentation of plots</a>
<ul>
<li class="chapter" data-level="9.1" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#the-basics"><i class="fa fa-check"></i><b>9.1</b> The basics</a></li>
<li class="chapter" data-level="9.2" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#the-caption-test"><i class="fa fa-check"></i><b>9.2</b> The caption test</a></li>
<li class="chapter" data-level="9.3" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#caption-or-title"><i class="fa fa-check"></i><b>9.3</b> Caption or title?</a></li>
<li class="chapter" data-level="9.4" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#customising-the-appearance-of-a-plot"><i class="fa fa-check"></i><b>9.4</b> Customising the appearance of a plot</a></li>
<li class="chapter" data-level="9.5" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#refining-a-plot-an-example"><i class="fa fa-check"></i><b>9.5</b> Refining a plot: an example</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#the-data-to-plot"><i class="fa fa-check"></i><b>9.5.1</b> The data to plot</a></li>
<li class="chapter" data-level="9.5.2" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#a-first-attempt-four-histograms"><i class="fa fa-check"></i><b>9.5.2</b> A first attempt: four histograms</a></li>
<li class="chapter" data-level="9.5.3" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#using-a-box-plot"><i class="fa fa-check"></i><b>9.5.3</b> Using a box plot</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#exercises"><i class="fa fa-check"></i><b>9.6</b> Exercises</a></li>
<li class="chapter" data-level="9.7" data-path="presentation-of-plots.html"><a href="presentation-of-plots.html#data-sources"><i class="fa fa-check"></i><b>9.7</b> Data sources</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="maps-with-leaflet.html"><a href="maps-with-leaflet.html"><i class="fa fa-check"></i><b>10</b> Maps with <code>leaflet</code></a>
<ul>
<li class="chapter" data-level="10.1" data-path="maps-with-leaflet.html"><a href="maps-with-leaflet.html#a-basic-map"><i class="fa fa-check"></i><b>10.1</b> A basic map</a></li>
<li class="chapter" data-level="10.2" data-path="maps-with-leaflet.html"><a href="maps-with-leaflet.html#indicating-points-on-a-map"><i class="fa fa-check"></i><b>10.2</b> Indicating points on a map</a></li>
<li class="chapter" data-level="10.3" data-path="maps-with-leaflet.html"><a href="maps-with-leaflet.html#exercise-2"><i class="fa fa-check"></i><b>10.3</b> Exercise</a></li>
<li class="chapter" data-level="10.4" data-path="maps-with-leaflet.html"><a href="maps-with-leaflet.html#further-reading-2"><i class="fa fa-check"></i><b>10.4</b> Further reading</a></li>
</ul></li>
<li class="part"><span><b>III Statistical analysis</b></span></li>
<li class="chapter" data-level="11" data-path="computing-using-loops.html"><a href="computing-using-loops.html"><i class="fa fa-check"></i><b>11</b> Computing using loops</a>
<ul>
<li class="chapter" data-level="11.1" data-path="computing-using-loops.html"><a href="computing-using-loops.html#repeating-a-process-with-a-for-loop"><i class="fa fa-check"></i><b>11.1</b> Repeating a process with a <code>for</code> loop</a></li>
<li class="chapter" data-level="11.2" data-path="computing-using-loops.html"><a href="computing-using-loops.html#example-cleaning-two-text-files"><i class="fa fa-check"></i><b>11.2</b> Example: cleaning two text files</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="computing-using-loops.html"><a href="computing-using-loops.html#the-core-code-block"><i class="fa fa-check"></i><b>11.2.1</b> The core code block</a></li>
<li class="chapter" data-level="11.2.2" data-path="computing-using-loops.html"><a href="computing-using-loops.html#identify-the-variables-we-need-to-specify"><i class="fa fa-check"></i><b>11.2.2</b> Identify the variables we need to specify</a></li>
<li class="chapter" data-level="11.2.3" data-path="computing-using-loops.html"><a href="computing-using-loops.html#create-an-empty-list-to-store-the-results"><i class="fa fa-check"></i><b>11.2.3</b> Create an empty list to store the results</a></li>
<li class="chapter" data-level="11.2.4" data-path="computing-using-loops.html"><a href="computing-using-loops.html#use-a-for-loop-to-run-the-code-block-multiple-times"><i class="fa fa-check"></i><b>11.2.4</b> Use a for loop to run the code block multiple times</a></li>
<li class="chapter" data-level="11.2.5" data-path="computing-using-loops.html"><a href="computing-using-loops.html#convert-the-list-to-a-data-frame"><i class="fa fa-check"></i><b>11.2.5</b> Convert the list to a data frame</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="computing-using-loops.html"><a href="computing-using-loops.html#example-averaging-over-groups"><i class="fa fa-check"></i><b>11.3</b> Example: averaging over groups</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="computing-using-loops.html"><a href="computing-using-loops.html#the-core-code-block-1"><i class="fa fa-check"></i><b>11.3.1</b> The core code block</a></li>
<li class="chapter" data-level="11.3.2" data-path="computing-using-loops.html"><a href="computing-using-loops.html#identify-the-variables-we-need-to-specify-1"><i class="fa fa-check"></i><b>11.3.2</b> Identify the variables we need to specify</a></li>
<li class="chapter" data-level="11.3.3" data-path="computing-using-loops.html"><a href="computing-using-loops.html#create-an-empty-vector-to-store-the-results"><i class="fa fa-check"></i><b>11.3.3</b> Create an empty vector to store the results</a></li>
<li class="chapter" data-level="11.3.4" data-path="computing-using-loops.html"><a href="computing-using-loops.html#use-a-for-loop-to-run-the-code-block-multiple-times-1"><i class="fa fa-check"></i><b>11.3.4</b> Use a <code>for</code> loop to run the code block multiple times</a></li>
<li class="chapter" data-level="11.3.5" data-path="computing-using-loops.html"><a href="computing-using-loops.html#convert-the-vector-to-a-data-frame"><i class="fa fa-check"></i><b>11.3.5</b> Convert the vector to a data frame</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="computing-using-loops.html"><a href="computing-using-loops.html#exercise-3"><i class="fa fa-check"></i><b>11.4</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="relationships-in-data.html"><a href="relationships-in-data.html"><i class="fa fa-check"></i><b>12</b> Relationships in data</a>
<ul>
<li class="chapter" data-level="12.1" data-path="relationships-in-data.html"><a href="relationships-in-data.html#covariance-and-correlation---recap"><i class="fa fa-check"></i><b>12.1</b> Covariance and correlation - recap</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="relationships-in-data.html"><a href="relationships-in-data.html#covariance"><i class="fa fa-check"></i><b>12.1.1</b> Covariance</a></li>
<li class="chapter" data-level="12.1.2" data-path="relationships-in-data.html"><a href="relationships-in-data.html#pearsons-correlation-coefficient"><i class="fa fa-check"></i><b>12.1.2</b> Pearson’s correlation coefficient</a></li>
<li class="chapter" data-level="12.1.3" data-path="relationships-in-data.html"><a href="relationships-in-data.html#spearmans-correlation-coefficient"><i class="fa fa-check"></i><b>12.1.3</b> Spearman’s correlation coefficient</a></li>
<li class="chapter" data-level="12.1.4" data-path="relationships-in-data.html"><a href="relationships-in-data.html#correlations-for-the-trees-data-set"><i class="fa fa-check"></i><b>12.1.4</b> Correlations for the <code>trees</code> data set</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="relationships-in-data.html"><a href="relationships-in-data.html#simple-linear-regression"><i class="fa fa-check"></i><b>12.2</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="relationships-in-data.html"><a href="relationships-in-data.html#fitting-the-simple-linear-regression-model-in-r"><i class="fa fa-check"></i><b>12.2.1</b> Fitting the simple linear regression model in R</a></li>
<li class="chapter" data-level="12.2.2" data-path="relationships-in-data.html"><a href="relationships-in-data.html#prediction-from-the-fitted-model"><i class="fa fa-check"></i><b>12.2.2</b> Prediction from the fitted model</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="relationships-in-data.html"><a href="relationships-in-data.html#exploring-variation-over-time"><i class="fa fa-check"></i><b>12.3</b> Exploring variation over time</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="relationships-in-data.html"><a href="relationships-in-data.html#trends"><i class="fa fa-check"></i><b>12.3.1</b> Trends</a></li>
<li class="chapter" data-level="12.3.2" data-path="relationships-in-data.html"><a href="relationships-in-data.html#seasonality"><i class="fa fa-check"></i><b>12.3.2</b> Seasonality</a></li>
<li class="chapter" data-level="12.3.3" data-path="relationships-in-data.html"><a href="relationships-in-data.html#temporal-dependence"><i class="fa fa-check"></i><b>12.3.3</b> Temporal dependence</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="relationships-in-data.html"><a href="relationships-in-data.html#exercise-4"><i class="fa fa-check"></i><b>12.4</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="imputing-missing-data.html"><a href="imputing-missing-data.html"><i class="fa fa-check"></i><b>13</b> Imputing missing data</a>
<ul>
<li class="chapter" data-level="13.1" data-path="imputing-missing-data.html"><a href="imputing-missing-data.html#visualising-missing-data"><i class="fa fa-check"></i><b>13.1</b> Visualising missing data</a></li>
<li class="chapter" data-level="13.2" data-path="imputing-missing-data.html"><a href="imputing-missing-data.html#exercise-5"><i class="fa fa-check"></i><b>13.2</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">MPS223 - Mathematics and Statistics in Action</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="relationships-in-data" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Section 12</span> Relationships in data<a href="relationships-in-data.html#relationships-in-data" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>In this section, let’s consider a built-in data frame in R called <code>trees</code> that contains measurements of the height (in ft), volume (in cubic ft) and diameter (in inches; measured at 4ft 6in above the ground) of the timber in 31 felled black cherry trees. We can load the data into the R environment as follows. (Note: the help documentation for this data set [at <code>help(trees)</code>] indicates that the diameter is erroneously labelled ‘Girth’ in the data frame in R - we will correct this here.)</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="relationships-in-data.html#cb143-1" tabindex="-1"></a><span class="fu">data</span>(trees)</span>
<span id="cb143-2"><a href="relationships-in-data.html#cb143-2" tabindex="-1"></a><span class="fu">colnames</span>(trees) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Diameter&quot;</span>,<span class="st">&quot;Height&quot;</span>,<span class="st">&quot;Volume&quot;</span>)</span>
<span id="cb143-3"><a href="relationships-in-data.html#cb143-3" tabindex="-1"></a><span class="fu">head</span>(trees)</span></code></pre></div>
<pre><code>##   Diameter Height Volume
## 1      8.3     70   10.3
## 2      8.6     65   10.3
## 3      8.8     63   10.2
## 4     10.5     72   16.4
## 5     10.7     81   18.8
## 6     10.8     83   19.7</code></pre>
<p>An initial exploration for any relationships between variables in a data set can be made via plotting. Here, we will use pairwise scatter plots to explore for pairwise relationships in the trees data, using the ‘base graphics’ command <code>pairs()</code>:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="relationships-in-data.html#cb145-1" tabindex="-1"></a><span class="fu">pairs</span>(trees, <span class="at">upper.panel=</span><span class="cn">NULL</span>, <span class="at">pch=</span><span class="dv">19</span>)</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-129-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Clearly, the <code>Diameter</code> and <code>Volume</code> of the trees has the strongest relationship, and the pairwise relationships between these variables and <code>Height</code> are weaker. In all cases, the relationships look to be relatively linear. Let’s now look into how we can quantify these relationships more formally.</p>
<div id="covariance-and-correlation---recap" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> Covariance and correlation - recap<a href="relationships-in-data.html#covariance-and-correlation---recap" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s first consider the relationship between the diameter and volume of the trees. For the <span class="math inline">\(i\)</span>-th tree, let <span class="math inline">\(x_i\)</span> be its diameter (in inches) and <span class="math inline">\(y_i\)</span> its volume (in cubic ft), for <span class="math inline">\(i=1,\ldots,31\)</span>. So, we have paired observations <span class="math inline">\((x_1=8.3, y_1=10.3)\)</span>, <span class="math inline">\((x_2=8.6, y_2=10.3)\)</span>, <span class="math inline">\((x_3=8.8, y_3=10.2)\)</span> and so on.</p>
<div id="covariance" class="section level3 hasAnchor" number="12.1.1">
<h3><span class="header-section-number">12.1.1</span> Covariance<a href="relationships-in-data.html#covariance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<hr>
<div class="definition">
<p><span id="def:defCovariance" class="definition"><strong>Definition 12.1  (Covariance) </strong></span>For pairs of observations <span class="math inline">\((x_1,y_1), (x_2, y_2),\ldots,(x_n,y_n)\)</span> we define their sample covariance to be
<span class="math display">\[
s_{xy}=\frac{1}{n-1}\sum_{i=1}^n(x_i - \bar{x})(y_i - \bar{y}),
\]</span>
where <span class="math inline">\(\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i\)</span> and <span class="math inline">\(\bar{y} = \frac{1}{n}\sum_{i=1}^n y_i\)</span>.</p>
</div>
<hr>
<div id="calculating-a-covariance-in-r" class="section level4 hasAnchor" number="12.1.1.1">
<h4><span class="header-section-number">12.1.1.1</span> Calculating a covariance in R<a href="relationships-in-data.html#calculating-a-covariance-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In R, we can use the command <code>cov()</code> to calculate covariance. For example:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="relationships-in-data.html#cb146-1" tabindex="-1"></a><span class="fu">cov</span>(trees<span class="sc">$</span>Diameter, trees<span class="sc">$</span>Volume)</span></code></pre></div>
<pre><code>## [1] 49.88812</code></pre>
<p>and so <span class="math inline">\(s_{xy} = 49.9\)</span> to 1 d.p.</p>
</div>
</div>
<div id="pearsons-correlation-coefficient" class="section level3 hasAnchor" number="12.1.2">
<h3><span class="header-section-number">12.1.2</span> Pearson’s correlation coefficient<a href="relationships-in-data.html#pearsons-correlation-coefficient" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Covariances aren’t very informative on their own, as they will depend on the scale of measurement of the variables. <strong>Correlation coefficients</strong> are scale independent. There are different versions of the correlation coefficient.</p>
<hr>
<div class="definition">
<p><span id="def:defPearson" class="definition"><strong>Definition 12.2  (Pearson's correlation coefficient) </strong></span>For pairs of observations <span class="math inline">\((x_1,y_1), (x_2, y_2),\ldots,(x_n,y_n)\)</span> we define Pearson’s correlation coeffcient to be
<span class="math display">\[
r_{xy}=\frac{s_{xy}}{s_xs_y},
\]</span>
with <span class="math inline">\(s_{xy}\)</span> the covariance defined above, and
<span class="math display">\[
s_x = \sqrt{\frac{1}{n-1}\sum_{i=1}^n(x_i - \bar{x})^2},
\]</span>
<span class="math display">\[ s_y = \sqrt{\frac{1}{n-1}\sum_{i=1}^n(y_i - \bar{y})^2}.
\]</span></p>
</div>
<hr>
<p>Pearson’s correlation coefficient measures the strength of the <strong>linear</strong> association between the two variables and is bounded between -1 and 1. A positive correlation implies that as one quantity increases, the other is expected to increase, and a negative correlation implies that as one quantity increases, the other is expected to decrease.</p>
<div id="calculating-pearsons-correlation-coefficient-in-r" class="section level4 hasAnchor" number="12.1.2.1">
<h4><span class="header-section-number">12.1.2.1</span> Calculating Pearson’s correlation coefficient in R<a href="relationships-in-data.html#calculating-pearsons-correlation-coefficient-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To calculate Pearson’s correlation coefficient between the variables <code>Diameter</code> and <code>Volume</code> in the data frame <code>trees</code>, we use the command</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="relationships-in-data.html#cb148-1" tabindex="-1"></a><span class="fu">cor</span>(trees<span class="sc">$</span>Diameter, trees<span class="sc">$</span>Volume)</span></code></pre></div>
<pre><code>## [1] 0.9671194</code></pre>
<p>and so <span class="math inline">\(r_{xy}=0.97\)</span> to 2 d.p. This value is very large and positive in sign (very close to 1), and suggests a strong positive relationship between these two variables.</p>
</div>
</div>
<div id="spearmans-correlation-coefficient" class="section level3 hasAnchor" number="12.1.3">
<h3><span class="header-section-number">12.1.3</span> Spearman’s correlation coefficient<a href="relationships-in-data.html#spearmans-correlation-coefficient" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>An alternative to Pearson’s correlation coefficient is <strong>Spearman’s</strong> correlation coefficient.</p>
<hr>
<div class="definition">
<p><span id="def:defSpearman" class="definition"><strong>Definition 12.3  (Spearman's correlation coefficient) </strong></span>For pairs of observations <span class="math inline">\((x_1,y_1), (x_2, y_2),\ldots,(x_n,y_n)\)</span> we define Spearman’s correlation coefficient to be Pearson’s correlation coefficient calculated on the the <strong>ranks</strong> of observations.</p>
</div>
<hr>
<p>By using the ranks of the observations, Spearman’s correlation coefficient identifies the strength of any <strong>monotonic</strong> relationship in the data.</p>
<div id="example" class="section level4 hasAnchor" number="12.1.3.1">
<h4><span class="header-section-number">12.1.3.1</span> Example<a href="relationships-in-data.html#example" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For illustration, suppose we have the following data</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
<th align="center">5</th>
<th align="center">6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(x_i\)</span></td>
<td align="center">68</td>
<td align="center">2</td>
<td align="center">40</td>
<td align="center">20</td>
<td align="center">85</td>
<td align="center">97</td>
</tr>
<tr class="even">
<td align="center"><span class="math inline">\(y_i\)</span></td>
<td align="center">73</td>
<td align="center">26</td>
<td align="center">37</td>
<td align="center">1</td>
<td align="center">63</td>
<td align="center">68</td>
</tr>
</tbody>
</table>
<p>We first calculate the ranks of the observations (if <span class="math inline">\(x_i\)</span> gets a rank of 1, it means <span class="math inline">\(x_i\)</span> was the smallest out of <span class="math inline">\(x_1,\ldots,x_n\)</span>):</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(i\)</span></th>
<th align="center">1</th>
<th align="center">2</th>
<th align="center">3</th>
<th align="center">4</th>
<th align="center">5</th>
<th align="center">6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">rank(<span class="math inline">\(x_i\)</span>)</td>
<td align="center">4</td>
<td align="center">1</td>
<td align="center">3</td>
<td align="center">2</td>
<td align="center">5</td>
<td align="center">6</td>
</tr>
<tr class="even">
<td align="center">rank(<span class="math inline">\(y_i\)</span>)</td>
<td align="center">6</td>
<td align="center">2</td>
<td align="center">3</td>
<td align="center">1</td>
<td align="center">4</td>
<td align="center">5</td>
</tr>
</tbody>
</table>
<p>We then calculate Pearson’s correlation coefficient on the ranks, as if we have six pairs of observations (4, 6), (1, 2), <span class="math inline">\(\ldots\)</span> (6, 5).</p>
</div>
<div id="calculating-spearmans-correlation-coefficient-in-r" class="section level4 hasAnchor" number="12.1.3.2">
<h4><span class="header-section-number">12.1.3.2</span> Calculating Spearman’s correlation coefficient in R<a href="relationships-in-data.html#calculating-spearmans-correlation-coefficient-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In R, we just include an extra argument in the <code>cor()</code> command:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="relationships-in-data.html#cb150-1" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">68</span>, <span class="dv">2</span>, <span class="dv">40</span>, <span class="dv">20</span>, <span class="dv">85</span>, <span class="dv">97</span>)</span>
<span id="cb150-2"><a href="relationships-in-data.html#cb150-2" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">73</span>, <span class="dv">26</span>, <span class="dv">37</span>, <span class="dv">1</span>, <span class="dv">63</span>, <span class="dv">68</span>)</span>
<span id="cb150-3"><a href="relationships-in-data.html#cb150-3" tabindex="-1"></a><span class="fu">cor</span>(x, y, <span class="at">method =</span> <span class="st">&#39;spearman&#39;</span>)</span></code></pre></div>
<pre><code>## [1] 0.7714286</code></pre>
<p>(If we don’t specify a <code>method</code>, the default is to use Pearson’s.) To illustrate that this is just Pearson’s correlation coefficient calculated on the ranks, we can obtain the rankings in R with the command <code>rank()</code>, and then compare the above with</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="relationships-in-data.html#cb152-1" tabindex="-1"></a><span class="fu">rank</span>(x)</span></code></pre></div>
<pre><code>## [1] 4 1 3 2 5 6</code></pre>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="relationships-in-data.html#cb154-1" tabindex="-1"></a><span class="fu">rank</span>(y)</span></code></pre></div>
<pre><code>## [1] 6 2 3 1 4 5</code></pre>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="relationships-in-data.html#cb156-1" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">rank</span>(x), <span class="fu">rank</span>(y))</span></code></pre></div>
<pre><code>## [1] 0.7714286</code></pre>
</div>
</div>
<div id="correlations-for-the-trees-data-set" class="section level3 hasAnchor" number="12.1.4">
<h3><span class="header-section-number">12.1.4</span> Correlations for the <code>trees</code> data set<a href="relationships-in-data.html#correlations-for-the-trees-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We calculate the Pearson correlations between the variables of interest using the following code:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="relationships-in-data.html#cb158-1" tabindex="-1"></a>trees <span class="sc">%&gt;%</span></span>
<span id="cb158-2"><a href="relationships-in-data.html#cb158-2" tabindex="-1"></a>  <span class="fu">na.omit</span>() <span class="sc">%&gt;%</span></span>
<span id="cb158-3"><a href="relationships-in-data.html#cb158-3" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb158-4"><a href="relationships-in-data.html#cb158-4" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">2</span>)</span></code></pre></div>
<ul>
<li>The second line excludes any rows with missing values (the <code>cor()</code> command won’t work otherwise);</li>
<li>the third line will produce a matrix of Pearson correlations, in the form above;</li>
<li>the fourth line rounds all the numbers to two decimal places.</li>
</ul>
<p>The code above produces the following output:</p>
<pre><code>##          Diameter Height Volume
## Diameter     1.00   0.52   0.97
## Height       0.52   1.00   0.60
## Volume       0.97   0.60   1.00</code></pre>
<p>Note that the correlation of any variable with itself is always 1. By looking at these correlations (in absolute value), tentatively, we may conclude the following:</p>
<ul>
<li>trees with a larger diameter are likely to have a larger volume (correlation of 0.97);</li>
<li>taller trees tend to have a larger diameter (correlation of 0.52) and a larger volume (correlation of 0.60).</li>
</ul>
<p>These correlations match to the inferences we made using the pairwise scatter plots above. (The correlations are all fairly similar if we use Spearman’s correlation instead.)</p>
</div>
</div>
<div id="simple-linear-regression" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Simple linear regression<a href="relationships-in-data.html#simple-linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Our scatter plots and correlation values indicate to us that we have a linear relationship between the <code>Diameter</code> (<span class="math inline">\(x\)</span>) and <code>Volume</code> (<span class="math inline">\(y\)</span>) of the black cherry trees:</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="relationships-in-data.html#cb160-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb160-2"><a href="relationships-in-data.html#cb160-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> trees, <span class="fu">aes</span>(<span class="at">x =</span> Diameter, <span class="at">y =</span> Volume)) <span class="sc">+</span></span>
<span id="cb160-3"><a href="relationships-in-data.html#cb160-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb160-4"><a href="relationships-in-data.html#cb160-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tree Diameter (inches)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tree Volume (cubic ft)&quot;</span>, </span>
<span id="cb160-5"><a href="relationships-in-data.html#cb160-5" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Volume v&#39;s Diameter for 31 felled black cherry trees&quot;</span>,</span>
<span id="cb160-6"><a href="relationships-in-data.html#cb160-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Pearson&#39;s correlation = &quot;</span>,<span class="fu">round</span>(<span class="fu">cor</span>(trees<span class="sc">$</span>Diameter,trees<span class="sc">$</span>Volume),<span class="dv">2</span>)))</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-136-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>However, this doesn’t give us any information about what the straight line of the relationship actually is. <strong>How</strong> is the <code>Volume</code> related to the <code>Diameter</code>? To explore this, we can ‘model’ the relationship using a <strong>simple linear regression model</strong> (a linear model with one independent variable) to evaluate the linear relationship in detail.</p>
<p>This linear model is defined as follows:
<span class="math display">\[
  y_{i} = \beta_{0} + \beta_{1}x_{i} + \epsilon_{i}
\]</span>
where:</p>
<ul>
<li>the <span class="math inline">\(x\)</span>-variable (<code>Diameter</code>) is called the <strong>independent</strong> variable with observed values <span class="math inline">\(x_{i}\)</span>;</li>
<li>the <span class="math inline">\(y\)</span>-variable (<code>Volume</code>) is called the <strong>dependent</strong> variable with observed values <span class="math inline">\(y_{i}\)</span>;</li>
</ul>
<p>** <strong>We will use the independent variable to predict the dependent variable.</strong> **</p>
<ul>
<li><span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> are the model parameters:
<ul>
<li><span class="math inline">\(\beta_{0}\)</span> is the <strong>intercept</strong> of the straight line (<span class="math inline">\(y\)</span>, at <span class="math inline">\(x=0\)</span>);</li>
<li><span class="math inline">\(\beta_{1}\)</span> is the <strong>slope</strong> of the straight line (the change in the dependent variable <span class="math inline">\(y\)</span> for every unit change in the independent variable, <span class="math inline">\(x\)</span>);</li>
</ul></li>
<li><span class="math inline">\(\epsilon\)</span> is a <strong>residual error</strong> term (we assume that <span class="math inline">\(y\)</span> is related to <span class="math inline">\(x\)</span> with some random error).</li>
</ul>
<p>To ‘fit’ the model to the data we must estimate the parameters <span class="math inline">\(\beta_{0}\)</span> and <span class="math inline">\(\beta_{1}\)</span> from the data to obtain <span class="math inline">\(\hat{\beta_{0}}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span>. The most common approach is estimation via ‘least squares’, where the values <span class="math inline">\(\hat{\beta_{0}}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span> are selected such that the fitted line minimises the sum of squared residual errors to the data points. The plot below illustrates this method:</p>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-137-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>The parameter estimates are selected such that for the fitted line they correspond to (shown in red), the sum of the squared residuals (the distances from the data points to the fitted line for the dependent variable <span class="math inline">\(y\)</span>, shown in blue, squared) is minimised.</p>
<p>It turns out that there is an analytical solution for the parameter estimates here:</p>
<p><span class="math display">\[
\hat{\beta}_{1} = \frac{s_{xy}}{s_x^2} = r_{xy}\frac{s_{y}}{s_{x}} \qquad \textrm{and} \qquad \hat{\beta}_{0} = \bar{y} - \hat{\beta}_{1}\bar{x}
\]</span></p>
<p>where <span class="math inline">\(s_{x}\)</span>, <span class="math inline">\(s_{y}\)</span>, <span class="math inline">\(s_{xy}\)</span> and <span class="math inline">\(r_{xy}\)</span> are as defined above in the <a href="relationships-in-data.html#pearsons-correlation-coefficient">Pearson’s correlation coefficient</a> section. (See <a href="https://sites.google.com/sheffield.ac.uk/somasstudentintranet/programme-study-information/module-choice/somas-module-directory/somas-module-directory-202425/mas2010-statistical-inference-and-modelling">MPS223 - Statistical Inference and Modelling, Semester 2</a> for the full details of this result.)</p>
<div id="fitting-the-simple-linear-regression-model-in-r" class="section level3 hasAnchor" number="12.2.1">
<h3><span class="header-section-number">12.2.1</span> Fitting the simple linear regression model in R<a href="relationships-in-data.html#fitting-the-simple-linear-regression-model-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In practise, we can use R to fit the simple linear regression model and obtain the parameter estimates <span class="math inline">\(\hat{\beta_{0}}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span>. To fit this model in R, we use the <code>lm()</code> command:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="relationships-in-data.html#cb161-1" tabindex="-1"></a>trees_lm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Volume <span class="sc">~</span> Diameter, <span class="at">data=</span>trees)</span></code></pre></div>
<p>The first argument of this command holds the details of our model specification and is in the format of a ‘formula’: <span class="math inline">\(y \sim x\)</span>, which states that we want to model/predict our dependent variable <span class="math inline">\(y\)</span> (<code>Volume</code>) as a linear function of our independent variable <span class="math inline">\(x\)</span> (<code>Diameter</code>).</p>
<p>We can view the full details of the fitted model using the summary command:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="relationships-in-data.html#cb162-1" tabindex="-1"></a><span class="fu">summary</span>(trees_lm)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Volume ~ Diameter, data = trees)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -8.065 -3.107  0.152  3.495  9.587 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -36.9435     3.3651  -10.98 7.62e-12 ***
## Diameter      5.0659     0.2474   20.48  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.252 on 29 degrees of freedom
## Multiple R-squared:  0.9353, Adjusted R-squared:  0.9331 
## F-statistic: 419.4 on 1 and 29 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Let’s briefly examine the output here:</p>
<ul>
<li>At the top the output repeats the <code>Call</code>, defining the model we have asked it to fit.</li>
<li>Then, it provides information of the <code>Residuals</code>.</li>
<li>Then, we have the information on the <code>Coefficients</code> - our parameter estimates for <span class="math inline">\(\hat{\beta_{0}}\)</span> (‘intercept’) and <span class="math inline">\(\hat{\beta}_{1}\)</span> (‘Diameter’) [R will use the independent variable’s name in the call here]). In this table:
<ul>
<li>the first column holds the parameter estimates;</li>
<li>the second column provides an uncertainty estimate for each parameter estimate (these should be small compared to the estimate);</li>
<li>then the final 2 columns show the results of t-test’s on the importance of the inclusion of each parameter estimate in the model.<br />
</li>
</ul></li>
<li>Finally, at the bottom we have more information on the goodness of fit of the model. Particularly, the value of <span class="math inline">\(R^2\)</span> (labelled <code>Multiple R-Squared</code>) indicates the percentage of the variance in the data of the dependent variable that is explained by the model.</li>
</ul>
<div class="rmdnote">
<p>
For a simple linear regression model, the value of <span class="math inline"><span class="math inline">\(R^2\)</span></span> is related to the Pearson’s
correlation co-efficient: <span class="math inline"><span class="math inline">\(R^2=r_{xy}^2\)</span></span>.
</p>
<p>
[This is <strong>not</strong> true for a more complex linear model
that contains more than 1 independent variable. In that case <span class="math inline"><span class="math inline">\(R^2\)</span></span> still exists, but it is no longer the
same as the correlation as you have more dimensions, and so are no
longer fitting a straight line.]
</p>
</div>
<p>From the output above, we can state the following:</p>
<ul>
<li><span class="math inline">\(\hat{\beta}_{0} = -36.9\)</span> with error <span class="math inline">\(3.37\)</span>.</li>
<li><span class="math inline">\(\hat{\beta}_{1}= 5.07\)</span> with error <span class="math inline">\(0.25\)</span>.</li>
<li>Both <span class="math inline">\(\hat{\beta}_{0}\)</span> and <span class="math inline">\(\hat{\beta}_{1}\)</span> are needed in the model.</li>
<li>The model explains 94% of the variance in the output, Volume.</li>
<li>The fitted regression line from our linear model is:
<span class="math display">\[
y_{i} = -36.9 + 5.07x_{i}
\]</span>
(Volume = -36.9 + 5.07 x Diameter).
We can add the regression line to our scatter plot directly as follows:</li>
</ul>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="relationships-in-data.html#cb164-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> trees, <span class="fu">aes</span>(<span class="at">x =</span> Diameter, <span class="at">y =</span> Volume)) <span class="sc">+</span></span>
<span id="cb164-2"><a href="relationships-in-data.html#cb164-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb164-3"><a href="relationships-in-data.html#cb164-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tree Diameter (inches)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tree Volume (cubic ft)&quot;</span>, </span>
<span id="cb164-4"><a href="relationships-in-data.html#cb164-4" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Volume v&#39;s Diameter for 31 felled black cherry trees&quot;</span>,</span>
<span id="cb164-5"><a href="relationships-in-data.html#cb164-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Pearson&#39;s correlation = &quot;</span>,<span class="fu">round</span>(<span class="fu">cor</span>(trees<span class="sc">$</span>Diameter,trees<span class="sc">$</span>Volume),<span class="dv">2</span>))) <span class="sc">+</span></span>
<span id="cb164-6"><a href="relationships-in-data.html#cb164-6" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">slope =</span> <span class="fu">coef</span>(trees_lm)[[<span class="st">&quot;Diameter&quot;</span>]],</span>
<span id="cb164-7"><a href="relationships-in-data.html#cb164-7" tabindex="-1"></a>              <span class="at">intercept =</span> <span class="fu">coef</span>(trees_lm)[[<span class="st">&quot;(Intercept)&quot;</span>]],<span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-141-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Or, alternatively, we can use the <code>geom_smooth()</code> option in <code>ggplot</code> to generate and add the linear model fit as a trend line. Here, we must use the argument <code>method='lm'</code> to obtain a linear fit (as a default, <code>geom_smooth()</code> applies a non-linear model trend, the details of which are beyond the scope of MPS223).</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="relationships-in-data.html#cb165-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> trees, <span class="fu">aes</span>(<span class="at">x =</span> Diameter, <span class="at">y =</span> Volume)) <span class="sc">+</span></span>
<span id="cb165-2"><a href="relationships-in-data.html#cb165-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb165-3"><a href="relationships-in-data.html#cb165-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tree Diameter (inches)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tree Volume (cubic ft)&quot;</span>, </span>
<span id="cb165-4"><a href="relationships-in-data.html#cb165-4" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Volume v&#39;s Diameter for 31 felled black cherry trees&quot;</span>,</span>
<span id="cb165-5"><a href="relationships-in-data.html#cb165-5" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Pearson&#39;s correlation = &quot;</span>,<span class="fu">round</span>(<span class="fu">cor</span>(trees<span class="sc">$</span>Diameter,trees<span class="sc">$</span>Volume),<span class="dv">2</span>))) <span class="sc">+</span></span>
<span id="cb165-6"><a href="relationships-in-data.html#cb165-6" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&#39;lm&#39;</span>)</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-142-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>A nice feature of this plotting approach is that <code>geom_smooth()</code> automatically includes a 95% confidence interval around the fitted linear regression line. However, we note that the actual details of the line itself are not given by this approach and must be obtained by fitting the simple linear regression model directly, as described above.</p>
</div>
<div id="prediction-from-the-fitted-model" class="section level3 hasAnchor" number="12.2.2">
<h3><span class="header-section-number">12.2.2</span> Prediction from the fitted model<a href="relationships-in-data.html#prediction-from-the-fitted-model" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Our fitted model (the estimated linear regression equation) can be used to predict our dependent variable <span class="math inline">\(y\)</span> (the volume of the tree, in cubic ft) given the value of our independent variable <span class="math inline">\(x\)</span> (the diameter of the tree, in inches, measured at 4ft 6in above the ground).</p>
<div id="example-1" class="section level4 hasAnchor" number="12.2.2.1">
<h4><span class="header-section-number">12.2.2.1</span> Example<a href="relationships-in-data.html#example-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If we measure a tree diameter of <span class="math inline">\(x = 17\)</span> inches, what is the predicted volume of this tree from our model?</p>
<ol style="list-style-type: decimal">
<li><p>Computing this prediction manually, using the formula:
<span class="math display">\[
\hat{y} \;=\; -36.9 + 5.07x \;=\; -36.9 + (5.07\times17) \;=\; 49.3 \textrm{ cubic feet (to 1 d.p.).}
\]</span></p></li>
<li><p>Computing this prediction manually, using the plot:
<img src="EDA-R_files/figure-html/unnamed-chunk-143-1.png" width="576" style="display: block; margin: auto;" /></p></li>
<li><p>Computing this prediction using R:</p></li>
</ol>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="relationships-in-data.html#cb166-1" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Diameter=</span><span class="dv">17</span>) </span>
<span id="cb166-2"><a href="relationships-in-data.html#cb166-2" tabindex="-1"></a><span class="fu">predict</span>(trees_lm, newdata, <span class="at">se.fit=</span><span class="cn">TRUE</span>) </span></code></pre></div>
<pre><code>## $fit
##       1 
## 49.1761 
## 
## $se.fit
## [1] 1.201876
## 
## $df
## [1] 29
## 
## $residual.scale
## [1] 4.251988</code></pre>
<p>The standard error on this predicted value is very small compared to the predicted value itself. This suggests we have confidence in the accuracy of this prediction.</p>
<div class="rmdnote">
<p>
When we use a statistical model to make predictions, we must be
careful with respect to <strong>extrapolation</strong>. The fitted model
only has information about the dependent variable <span class="math inline"><span class="math inline">\(y\)</span></span> within the range of the data of the
independent variable, <span class="math inline"><span class="math inline">\(x\)</span></span>. Outside
the range of <span class="math inline"><span class="math inline">\(x\)</span></span>, predictions will
have much larger uncertainty and may not be valid.
</p>
<p>
For example, for the prediction of the tree volume <span class="math inline"><span class="math inline">\(y\)</span></span> here, the smallest tree diameter <span class="math inline"><span class="math inline">\(x\)</span></span> measured is &gt;8 inches. The intercept
of the fitted line is (<span class="math inline"><span class="math inline">\(x=0\)</span></span>, <span class="math inline"><span class="math inline">\(y=-36\)</span></span>), which means that a very small
diameter will result in negative volume being estimated. Hence, the
model is not valid for very small tree diameters and such extrapolation
would yield impossible results.
</p>
</div>
</div>
</div>
</div>
<div id="exploring-variation-over-time" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Exploring variation over time<a href="relationships-in-data.html#exploring-variation-over-time" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>When a variable in a data set varies over time it may be described as a <strong>time series</strong> variable and we may be interested in understanding that variation over time better.</p>
<p>A time series is an ordered collection of observations, obtained at successive times and collected in equally spaced time intervals. Time series occur in many application areas, and in particular relevance to our course project, in weather forecasting.</p>
<p>There is a whole branch of statistical modelling and inference techniques that are dedicated to time series analysis - we will explore some key features of a time series here from a simpler EDA perspective, but we will not cover the details of full time series modelling and forecasting - if you are interested in formally modelling time series data, you might want to consider taking the year 3 module: <a href="https://sites.google.com/sheffield.ac.uk/somasstudentintranet/programme-study-information/module-choice/somas-module-directory/somas-module-directory-202425/mas372-time-series">MPS319 - Time Series</a> next year.</p>
<p>In time series data, some <strong>key patterns</strong> in the data that we might explore are:</p>
<ol style="list-style-type: decimal">
<li>A <strong>trend</strong> in the data - does the data show any long-term pattern? (E.g. increasing, decreasing or no change.)</li>
<li><strong>Seasonality</strong> in the data - are there short-term patterns that occur within a short unit of time and repeat indefinitely? (E.g. a monthly cycle.)</li>
<li><strong>Temporal dependence</strong> in the data - is the observation at time <span class="math inline">\(t\)</span> dependent on the observation at time <span class="math inline">\(t-1\)</span>? (Or, time <span class="math inline">\(t-2\)</span>, <span class="math inline">\(t-3\)</span>, etc.)</li>
</ol>
<p>Let’s consider how we might use EDA to explore these. To illustrate, we will use the data contained in the file <code>AirPassengers_reformatted.csv</code>. This data is a reformatted version of the built-in R time series object called <code>AirPassengers</code>, which contains monthly totals of international airline passengers for an airline, in thousands, from 1949 to 1960. [See <code>help(AirPassengers)</code> for further details and a reference for this data.]</p>
<p>The data is read into R using the following commands (here, we also add a ‘decimal time’ variable to the data frame to aid in plotting the data):</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="relationships-in-data.html#cb168-1" tabindex="-1"></a>AirPassengerData <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/AirPassengers_reformatted.csv&quot;</span>)</span>
<span id="cb168-2"><a href="relationships-in-data.html#cb168-2" tabindex="-1"></a>Decimal_Year_Vec <span class="ot">&lt;-</span> AirPassengerData<span class="sc">$</span>year<span class="sc">+</span>(AirPassengerData<span class="sc">$</span>month<span class="sc">/</span><span class="dv">12</span>)<span class="sc">-</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">12</span>)</span>
<span id="cb168-3"><a href="relationships-in-data.html#cb168-3" tabindex="-1"></a>AirPassengerData <span class="ot">&lt;-</span> <span class="fu">mutate</span>(AirPassengerData,<span class="at">Decimal_Year =</span> Decimal_Year_Vec)</span>
<span id="cb168-4"><a href="relationships-in-data.html#cb168-4" tabindex="-1"></a><span class="fu">rm</span>(Decimal_Year_Vec)</span>
<span id="cb168-5"><a href="relationships-in-data.html#cb168-5" tabindex="-1"></a><span class="fu">head</span>(AirPassengerData)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##    year month AirPassengers Decimal_Year
##   &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;
## 1  1949     1           112        1949 
## 2  1949     2           118        1949.
## 3  1949     3           132        1949.
## 4  1949     4           129        1949.
## 5  1949     5           121        1949.
## 6  1949     6           135        1949.</code></pre>
<p>and we can visualise the Air Passenger data as a line plot:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="relationships-in-data.html#cb170-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>AirPassengerData, <span class="fu">aes</span>(<span class="at">x =</span> Decimal_Year, <span class="at">y =</span> AirPassengers)) <span class="sc">+</span></span>
<span id="cb170-2"><a href="relationships-in-data.html#cb170-2" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb170-3"><a href="relationships-in-data.html#cb170-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Number of international air passengers </span><span class="sc">\n</span><span class="st"> (monthly; in thousands)&quot;</span>)</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-147-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>Clearly, this data exhibits a trend, seasonality and potentially has temporal dependence. We will now explore these using EDA methods.</p>
<div id="trends" class="section level3 hasAnchor" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Trends<a href="relationships-in-data.html#trends" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Although this is not strictly statistically ‘valid’, as we are not accounting for any dependence/correlation in the time variable (<span class="math inline">\(x\)</span>) here, we can use <code>ggplot()</code> to explore the presence of, and comment on, any long-term trends in our data over time by including the <code>geom_smooth()</code> argument with our plot. (The default of <code>geom_smooth()</code> is to fit a non-linear trend over the data.)</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="relationships-in-data.html#cb171-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>AirPassengerData, <span class="fu">aes</span>(<span class="at">x =</span> Decimal_Year, <span class="at">y =</span> AirPassengers)) <span class="sc">+</span></span>
<span id="cb171-2"><a href="relationships-in-data.html#cb171-2" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb171-3"><a href="relationships-in-data.html#cb171-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Number of international air passengers </span><span class="sc">\n</span><span class="st"> (monthly; in thousands)&quot;</span>) <span class="sc">+</span></span>
<span id="cb171-4"><a href="relationships-in-data.html#cb171-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-148-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>In this example, there is clearly an increasing trend in the number of international air passengers travelling over time, over the observed period of 1949-1960.</p>
</div>
<div id="seasonality" class="section level3 hasAnchor" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Seasonality<a href="relationships-in-data.html#seasonality" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Seasonality in a time series shows as short-term patterns that occur within a short unit of time and repeat over the length of the observed data. Most commonly in environmental data, we see seasonal effects play out across yearly time intervals in the data (i.e. changes/variation in the variable quantity dependent on the season and/or month of the year).</p>
<p>Looking at our line plot of the air passenger data above, we can see that there is clearly a cycle of variation within each year of the data, with lower passenger numbers occurring in winter months and higher passenger numbers occurring over summer months. [Note that the variation in the seasonal pattern increases with time, but that this seems in proportion with the increasing magnitude (trend) of the number of passengers observed.]</p>
<p>To investigate this seasonal behaviour further and quantify the seasonal variation more explicitly, we can break the data down into groups (say individual months or seasons) and apply our EDA techniques over those groupings to evaluate summaries of the patterns. For example, we might produce a figure containing box plots of the air passenger data, grouping the data by the month of the year:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="relationships-in-data.html#cb172-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> AirPassengerData, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(month), <span class="at">y =</span> AirPassengers)) <span class="sc">+</span></span>
<span id="cb172-2"><a href="relationships-in-data.html#cb172-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb172-3"><a href="relationships-in-data.html#cb172-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Month&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Number of international air passengers </span><span class="sc">\n</span><span class="st"> (monthly; in thousands)&quot;</span>)</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-149-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>This figure shows that the monthly median number of international air passengers (shown by the central line in each box plot) over the period 1949-1960 is higher in summer months like July (<code>month = 7</code>) than it is in winter months like January (<code>month = 1</code>). The observations in the month of July also have wider variation, and a wider range. [Note: Consider how the above figure could be improved to increase clarity, e.g. the labelling on the x-axis could be much clearer!]</p>
<p>Further / alternative ways to investigate seasonal patterns might be:</p>
<ul>
<li>to produce key summary statistics highlighting important differences;</li>
<li>to compute seasonal average air passenger numbers for each year (using a <code>for</code> loop - see the <a href="computing-using-loops.html#computing-using-loops">Computing using loops</a> section), and investigate the differences in those;</li>
<li>to create line plots that show the data for each month as separate lines over the period.</li>
</ul>
<p>** <strong>Think creatively about how you might visualise the patterns!</strong> **</p>
</div>
<div id="temporal-dependence" class="section level3 hasAnchor" number="12.3.3">
<h3><span class="header-section-number">12.3.3</span> Temporal dependence<a href="relationships-in-data.html#temporal-dependence" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To explore temporal dependence in the data (how an observation at a given time depends on the observations that come directly before it) we will examine how our observed data at time <span class="math inline">\(t\)</span> depends on the observed data at time <span class="math inline">\((t-1)\)</span>. We can calculate an approximate understanding of this as follows.</p>
<p>Firstly, we create a new data frame that contains pairs of observations <span class="math inline">\((y_{t}, y_{t-1})\)</span>:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="relationships-in-data.html#cb173-1" tabindex="-1"></a>N_total <span class="ot">&lt;-</span> <span class="fu">dim</span>(AirPassengerData)[<span class="dv">1</span>]</span>
<span id="cb173-2"><a href="relationships-in-data.html#cb173-2" tabindex="-1"></a></span>
<span id="cb173-3"><a href="relationships-in-data.html#cb173-3" tabindex="-1"></a>AirPassengerData_Timelag <span class="ot">&lt;-</span> AirPassengerData[<span class="sc">-</span><span class="dv">1</span>,<span class="sc">-</span><span class="dv">4</span>]</span>
<span id="cb173-4"><a href="relationships-in-data.html#cb173-4" tabindex="-1"></a>AirPassengers_lag1_Vec <span class="ot">&lt;-</span> AirPassengerData<span class="sc">$</span>AirPassengers[<span class="sc">-</span>N_total]</span>
<span id="cb173-5"><a href="relationships-in-data.html#cb173-5" tabindex="-1"></a></span>
<span id="cb173-6"><a href="relationships-in-data.html#cb173-6" tabindex="-1"></a>AirPassengerData_Timelag <span class="ot">&lt;-</span> <span class="fu">mutate</span>(AirPassengerData_Timelag, <span class="at">AirPassengers_lag1 =</span> AirPassengers_lag1_Vec)</span>
<span id="cb173-7"><a href="relationships-in-data.html#cb173-7" tabindex="-1"></a><span class="fu">head</span>(AirPassengerData_Timelag)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##    year month AirPassengers AirPassengers_lag1
##   &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt;              &lt;dbl&gt;
## 1  1949     2           118                112
## 2  1949     3           132                118
## 3  1949     4           129                132
## 4  1949     5           121                129
## 5  1949     6           135                121
## 6  1949     7           148                135</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="relationships-in-data.html#cb175-1" tabindex="-1"></a><span class="fu">rm</span>(N_total, AirPassengers_lag1_Vec)</span></code></pre></div>
<p>Here, in this new data frame called <code>AirPassengerData_Timelag</code> we have created a new column called <code>AirPassengers_lag1</code>, which is the original <code>AirPassengers</code> column of the data frame <code>AirPassengerData</code>, ‘time-lagged’ by one observation (1 month). Hence, in the new data frame we can see that we no longer have an observation line for January 1949 - it has been removed as there is no value for this observation for time <span class="math inline">\((t-1)\)</span> - and, each value in the <code>AirPassengers_lag1</code> column (<span class="math inline">\(y_{t-1}\)</span>) appears on the line above in the <code>AirPassengers</code> column (as <span class="math inline">\(y_{t}\)</span>). Data that is time-lagged by one observation in this way (column <code>AirPassengers_lag1</code>) is often referred to as a data series <strong>at time lag 1</strong>.</p>
<p>Let’s now make a scatter plot of <span class="math inline">\(y_{t}\)</span> v’s <span class="math inline">\(y_{t-1}\)</span> to investigate for any temporal dependence at lag 1 for this data:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="relationships-in-data.html#cb176-1" tabindex="-1"></a>Temp_Correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(AirPassengerData_Timelag<span class="sc">$</span>AirPassengers, AirPassengerData_Timelag<span class="sc">$</span>AirPassengers_lag1)</span>
<span id="cb176-2"><a href="relationships-in-data.html#cb176-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> AirPassengerData_Timelag, <span class="fu">aes</span>(<span class="at">x =</span> AirPassengers_lag1, <span class="at">y =</span> AirPassengers)) <span class="sc">+</span></span>
<span id="cb176-3"><a href="relationships-in-data.html#cb176-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb176-4"><a href="relationships-in-data.html#cb176-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of international air passengers at time (t-1), in thousands&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Number of international air </span><span class="sc">\n</span><span class="st">passengers at time t, in thousands&quot;</span>, </span>
<span id="cb176-5"><a href="relationships-in-data.html#cb176-5" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Monthly temporal dependence in the air passenger data&quot;</span>,</span>
<span id="cb176-6"><a href="relationships-in-data.html#cb176-6" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste0</span>(<span class="st">&quot;Pearson&#39;s correlation = &quot;</span>,<span class="fu">round</span>(Temp_Correlation,<span class="dv">2</span>)))</span></code></pre></div>
<p><img src="EDA-R_files/figure-html/unnamed-chunk-151-1.png" width="576" style="display: block; margin: auto;" /></p>
<p>We can clearly see a strong dependence beetween the observations at time <span class="math inline">\(t\)</span> and the lag 1 observations at time <span class="math inline">\((t-1)\)</span>.</p>
<p>We can use Pearson’s correlation coefficient to quantify the strength of this dependence. This calculation is included with the figure above and we obtain a correlation value of <span class="math inline">\(r_{xy} = 0.96\)</span>. This indicates a very strong linear relationship for this temporal dependence, which the scatter plot above verifies. This correlation estimate is in fact an approximation for a time series quantity called the <strong>autocorrelation at lag 1</strong>. The linear relationship could also be further quantified using <a href="relationships-in-data.html#simple-linear-regression">Simple linear regression</a>, if required.</p>
</div>
</div>
<div id="exercise-4" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Exercise<a href="relationships-in-data.html#exercise-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="task">
<div class="exercise">
<p><span id="exr:unlabeled-div-7" class="exercise"><strong>Exercise 12.1  </strong></span>For the monthly mean wind speed measurements (m/sec) in Exercise 11.1 (data file <code>Monthly_Wind_MA_1980-95.csv</code>), investigate the variation in the data over time:</p>
<ol style="list-style-type: decimal">
<li><p>Make some plots to investigate the presence of any long term trend in the data over time and any seasonal patterns in the data.</p></li>
<li><p>Explore the temporal dependence in the data by plotting <span class="math inline">\(y_{t}\)</span> against <span class="math inline">\(y_{t-1}\)</span>.</p></li>
<li><p>Quantify the strength of this relationship using both Pearson’s correlation coefficient and Spearman’s correlation coefficient. Describe the relationship you have quantified with words.</p></li>
<li><p>Use simple linear regression to further quantify a linear relationship between <span class="math inline">\(y_{t}\)</span> and <span class="math inline">\(y_{t-1}\)</span>. Describe the fitted model. How useful is the wind speed at time <span class="math inline">\((t-1)\)</span> for describing the wind speed at time <span class="math inline">\(t\)</span>? How much would you trust a prediction from this simple linear regression model?</p></li>
</ol>
</div>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="computing-using-loops.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="imputing-missing-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
